# Generated by Django 4.1 on 2022-08-25 08:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('shop', '0004_rutag_rutaggeditem_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='shop.RuTaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
