# Generated by Django 4.1 on 2022-08-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3',
        ),
    ]
