# Generated by Django 4.1 on 2022-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Атрибуты по праздникам',
                'ordering': ('-slug',),
            },
        ),
        migrations.DeleteModel(
            name='RuTag',
        ),
        migrations.DeleteModel(
            name='RuTaggedItem',
        ),
        migrations.AddField(
            model_name='product',
            name='holiday',
            field=models.ManyToManyField(to='shop.holiday', verbose_name='Праздники'),
        ),
    ]
