# Generated by Django 4.1 on 2022-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_holiday_delete_rutag_delete_rutaggeditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='holiday',
            field=models.ManyToManyField(blank=True, to='shop.holiday', verbose_name='Праздники'),
        ),
    ]
