# Generated by Django 4.1 on 2022-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
        ('shop', '0011_alter_product_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.AlterField(
            model_name='product',
            name='holiday',
            field=models.ManyToManyField(blank=True, to='attribute.holiday', verbose_name='Праздники'),
        ),
    ]
