# Generated by Django 4.1 on 2022-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_age_event_profession_subject_travel_and_more'),
        ('shop', '0012_delete_holiday_alter_product_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='holiday',
            field=models.ManyToManyField(blank=True, to='attribute.holiday', verbose_name='К праздникам'),
        ),
    ]
