# Generated by Django 4.1 on 2022-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_age_event_profession_subject_travel_and_more'),
        ('shop', '0014_product_age_product_event_product_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.age', verbose_name='По возрасту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.event', verbose_name='К памятным событиям'),
        ),
        migrations.AlterField(
            model_name='product',
            name='holiday',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.holiday', verbose_name='К праздникам'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.profession', verbose_name='По профессиям'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.subject', verbose_name='По темам'),
        ),
        migrations.AlterField(
            model_name='product',
            name='travel',
            field=models.ManyToManyField(blank=True, related_name='products', to='attribute.travel', verbose_name='Путешественникам'),
        ),
    ]
