# Generated by Django 4.1 on 2022-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_age_alter_product_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Альтернативный текст'),
        ),
    ]
