# Generated by Django 4.1 on 2022-08-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_options_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-available', '-created'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
