# Generated by Django 4.1 on 2022-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'По возрасту',
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Памятное событие',
                'verbose_name_plural': 'К памятным событиям',
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'По профессиям',
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'По темам',
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Путешествик',
                'verbose_name_plural': 'Путешественникам',
                'ordering': ('-slug',),
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('-slug',), 'verbose_name': 'Праздник', 'verbose_name_plural': 'К праздникам'},
        ),
    ]
