# Generated by Django 4.1 on 2022-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('process', 'В работе'), ('in-delivery', 'Доставляется'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=15, verbose_name='Статус заявки'),
        ),
    ]
