# Generated by Django 4.1 on 2022-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(default=0, max_length=150, verbose_name='Идентификатор оплаты'),
            preserve_default=False,
        ),
    ]
