# Generated by Django 4.1 on 2022-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлен счет'),
        ),
    ]
