# Generated by Django 4.1 on 2022-08-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pay_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Идентификатор оплаты'),
        ),
    ]
